toolbox:
  PROBING: "ajukan pertanyaan klarifikasi singkat"
  CLARIFYING: "konfirmasi pemahamanmu"
  PARAPHRASING: "parafrase pesan pengguna"
  REFLECTING: "cerminkan perasaan pengguna"
  OPEN_ENDED_QUESTIONS: "ajak pengguna memberi lebih banyak detail"
  CLOSED_ENDED_QUESTIONS: "dapatkan fakta-fakta spesifik"
  SUMMARIZING: "ringkas secara singkat poin-poin utama"
  CONFRONTATION: "ingatkan dengan lembut jika ada ketidakkonsistenan"
  REASSURANCE_ENCOURAGEMENT: "beri dukungan dan penenangan"
  NEUTRAL_ACKNOWLEDGEMENT: "berikan pengakuan singkat yang netral"

synonyms:
  reflection: REFLECTING
  mirroring: REFLECTING
